# Generated by Django 5.0.4 on 2024-11-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_cook_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish", "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"verbose_name": "Dish_type", "verbose_name_plural": "Dish_types"},
        ),
    ]
